server:
  port: 8080

custom:
  diploma:
    accountService:
      url: http://localhost:8081
    paymentService:
      url: http://localhost:8082
    calculatorService:
      url: http://localhost:8083