server:
  port: 8080

custom:
  diploma:
    accountService:
      url: http://localhost:8081
    paymentService:
      url: http://localhost:8082

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic


